### ISSUE TITLE
how to insert todo or notes to specified title

### ISSUE THREAD

**Issue by smartepsh** [alexandergogl/alfred-org-mode-workflow#3]
Hi, Thanks for developing this workflow first. It is very useful to me.

Now, all todos and notes will insert into `inbox_file` as `level 1 heading`. 
But in my case, I prefer to put them under a certain heading, like `Temporary` or `TODOs`. 

My question is, 
How to setup for this feature now ? (If support it now)
or Will you support this feature in the future?

**Comment by alexandergogl** [comment]
The option is there, I just hadn't exposed it as an alfred workflow environment variable. But now you can. See README.
