### ISSUE TITLE
Please update for Alfred 4 and M1 chipped macs

### ISSUE THREAD

**Issue by wakatara** [alexandergogl/alfred-org-mode-workflow#4]
I just came back to org-mode so would love it if this supported newer python (even homebrew installed) python on intel and M1/M2 macs. 

Standard python appears to by python2 now (not python) and python3 is installed generally via homebrew.

For M1 types homebrew instlls python in opt/homebrew/bin and not /usr/local/bin like Intel chipped macs.

(and thanks for creating this!)

**Comment by alexandergogl** [comment]
Hi!

I've updated the code to work with python 3.9 and published a new release (v2). On my machine, it works with homebrew and anaconda paths for python.

Please have a look at it and confirm whether it works or not.

**Comment by wakatara** [comment]
Thanks! I've downloaded and insstalled the new workflow (and Alfred 5). 
I moved the language over to `/usr/bin/python3` and

1. Set org.inbox_file to "/Users/daryl/Documents/org/inbox.org"
2. Set the inteher in org.heading_suffi to '2'
3. Set org.delimiter to '--'

However, for the todo items when I type them in they are not being created in the inbox.org.

Any further info I can use to help you diagnose what the issue might be?

**Comment by alexandergogl** [comment]
Please enable Alfred's debugging mode and post the error message.


![Bildschirmfoto 2023-01-19 um 22 07 57](https://user-images.githubusercontent.com/6707564/213560120-62a47d42-2d91-44bd-b5dc-765213687db2.png)

**Comment by wakatara** [comment]
Heya! Alrighty, this is what I am seeing from the debugging output (handy. did not know you could do that with the workflows).

``` python
[17:59:08.700] Logging Started...
[17:59:43.538] org-mode-capture[Keyword] Processing complete
[17:59:43.540] org-mode-capture[Keyword] Passing output 'Test item to be added to inbox org.  :perso:w03:' to Run Script
[17:59:43.652] ERROR: org-mode-capture[Run Script] Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: '/Users/daryl/Documents/org/inbox.org'
[17:59:43.657] org-mode-capture[Run Script] Processing complete
[17:59:43.658] org-mode-capture[Run Script] Passing output '' to Post Notification
```
I'm not entirely sure why it wold raise a key error there unless I'm supposed to set the variables eleshere (and even then...). 

Just in case it's important, I'm on OSX Ventura 13.1 and while I don't think it's relevant, the org directory is a symlink to iCloud (so my org-mode works with BeOrg on the iPhone.). 

lemme know what you think!

**Comment by wakatara** [comment]
Ahhhh... found it. I did not realize there was an environments variable panel now rather than modifying the scripts manually. I have it working. will kick the tires and see if I find anything else not related to PEBCAK

Thanks so much !

**Comment by alexandergogl** [comment]
Yes, there were some great changes in the last two Alfred major releases :) If you are interested, then you can also download the [v2.2](https://github.com/alexandergogl/alfred-org-mode-workflow/releases/tag/v2.2) [Latest](https://github.com/alexandergogl/alfred-org-mode-workflow/releases/latest) release, where I have exposed all variables as Alfred's new user customisable variables.
