### ISSUE TITLE
[Bug] alfred-org-mode-workflow not showing up in possible Actions after install

### ISSUE THREAD

**Issue by wakatara** [alexandergogl/alfred-org-mode-workflow#5]
Version 2.2

Installed the new version of the workflow and reconfigured it (nb: using Python 3.10 and at homebrew location of `/opt/homebrew/bin/python3`. The config variables appear to be all correct and all orange ones have been filled in. 

However, when I call up my Alfred palette and type "todo", "note" or "insp", none of those actions appear as possible options.

OSX 13.1 Ventura. M1 chipped mac.

Also to note: I overwrote the older version of the workflow by simply double clicking on this one, but have deleted it now and reinstalled it and reconfigged it and still having the same behaviour.

**Comment by wakatara** [comment]
Ignore... I think the issue was having the homebrew version of python in there rather than `/usr/bin/python3` (which is just a symlink). This seems to have fixed it when I changed that as the variable.

**Comment by alexandergogl** [comment]
OK! Please notify me if you run into future problems.

**Comment by alexandergogl** [comment]
Just to clarify this: I ran a successful test with homebrew's python 3 symlinked to path `/usr/local/bin/python`
